## Arithmetic Operations

In [1]:
import numpy as np  

# Create a NumPy array  
arr = np.array([1, 2, 3, 4, 5])  
print("Array:", arr)  

# Perform arithmetic operations  
print("Add 5:", arr + 5)  
print("Multiply by 2:", arr * 2)  

Array: [1 2 3 4 5]
Add 5: [ 6  7  8  9 10]
Multiply by 2: [ 2  4  6  8 10]


## Array Statistics

In [3]:
import numpy as np  

# Create a NumPy array  
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  

# Calculate mean, median, and standard deviation  
print("Mean:", np.mean(arr))  
print("Median:", np.median(arr))  
print("Standard Deviation:", np.std(arr))  

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


## Reshaping Arrays

In [5]:
import numpy as np  

# Create a NumPy array  
arr = np.arange(1, 13)  

# Reshape the array into 3x4 2D array  
reshaped_arr = arr.reshape(3, 4)  
print("Reshaped Array:\n", reshaped_arr)  

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Array Indexing

In [7]:
import numpy as np  

# Create a NumPy array  
arr = np.array([10, 20, 30, 40, 50])  

# Demonstrate indexing and slicing  
print("First Element:", arr[0])  
print("Last Element:", arr[-1])  
print("Slice (1 to 3):", arr[1:4])  

First Element: 10
Last Element: 50
Slice (1 to 3): [20 30 40]


## Array concatenation

In [9]:
import numpy as np  

# Create two NumPy arrays  
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  

# Concatenate the arrays  
concatenated = np.concatenate((arr1, arr2))  
print("Concatenated Array:", concatenated)  

Concatenated Array: [1 2 3 4 5 6]


## Boolean Indexing

In [11]:
import numpy as np  

# Create a NumPy array  
arr = np.array([1, 2, 3, 4, 5])  

# Use boolean condition to filter the array  
filtered_arr = arr[arr > 2]  
print("Filtered Array (greater than 2):", filtered_arr) 

Filtered Array (greater than 2): [3 4 5]


## Dot Product

In [13]:
import numpy as np  

# Create two NumPy arrays  
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  

# Calculate the dot product  
dot_product = np.dot(arr1, arr2)  
print("Dot Product:", dot_product)  

Dot Product: 32


## Linear Algebra

In [26]:
matrix=np.array([[1,2],[3,4]])
determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
print("Determinant:",determinant)
print("inverse:\n",inverse)

Determinant: -2.0000000000000004
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
